### ISSUE TITLE
Regex matching rule

### ISSUE THREAD

**Issue by kiootic** [oursky/gitlint-bot#84]
Some projects use custom commit message convention, such as:
```
ci: Add deploy notification
```

It triggers false positive on rule `subject-capitalize-first`. We may want to provide a generic regex rule to match for this case, e.g. :
```js
rules:
  match-regex: [on, null, "^\p{Ll}+: \p(Lu}.+$"]
```

**Comment by Arthelon** [comment]
The commit message convention followed that cause these false positives follow the conventional commits message format which. The external parser exposes `.subject` to match the part of the commit header that we want. 

If we want to use our own regex, I don't think it should be provided as a rule but as a top-level config field since it affects all rules. For example:

```
preset: default
match-regex: ...
rules:
      subject-no-trailing-whitespace: 
          - off
```

**Comment by kiootic** [comment]
I agree, we shouldn't ask user to parse conventional commit messages in the regex. I suppose `header-regex` in your config example is referring to (`headerPattern`)(https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-commits-parser#headerpattern) of the parser?

Your configuration seems good enough. I suppose we can make the following changes:
- Add `header-regex` to config, default to the conventional commit message format regex.
- Change uses of `commit.header` to `commit.subject ?? commit.header` in all rules.

Does that sounds good to you?

**Comment by Arthelon** [comment]
yeah, this sounds good

**Comment by kiootic** [comment]
Do you want to have a go at solving this issue? Otherwise I'll take some time to fix it later this week.
